---
vpc_region: 'us-east-1'
keypair: 'akeypair'
security_groups: 'docnow-app-group'
instance_type: 't2.micro'

image: 'ami-cd0f5cb6'
group_name: 'docnow-test'
iam_profile: "noaccess"
ssh_public_key: '/path/to/home/.ssh/id_rsa.pub'
environment_public_ssh_key_name: 'generateddocnowsshkey'
docker_compose_version: '1.15.0'

aws_access_key: 'yourawsaccesskey'
aws_secret_key: 'yourawssecretkey'


volumes: []

