---
# tasks file for redis
- name: install gnu privacy guard
  ansible.builtin.apt:
    name: "dirmngr"
    state: present

- name: Add from PPA and install its signing key on Debian target
  ansible.builtin.apt_repository:
    repo: "ppa:redislabs/redis"
    update_cache: true

- name: install redis
  ansible.builtin.apt:
    name: "{{ redis_packages }}"
    state: present

- name: start and enable redis
  service:
    name: "redis-server"
    state: started
    enabled: true
  when:
    - running_on_server
