---
# tasks file for redis
- name: Add nginx stable repository from PPA and install its signing key on Debian target
  ansible.builtin.apt_repository:
    repo: "ppa:redislabs/redis"
    update_cache: true

- name: install redis
  apt:
    name: "{{ redis_packages }}"
    state: present

- name: start and enable redis
  service:
    name: "redis-server"
    state: started
    enabled: true
