---
es_major_version: '5.x'
es_version: '5.6.8'
elasticsearch_network_host: '{{ ansible_eth0.ipv4.address }}'
elasticsearch_http_port: 9200
elasticsearch_script_inline: true
elasticsearch_script_indexed: true
