---
- name: install nginx
  apt:
    name: nginx-full
    update_cache: yes
    state: present

- name: remove default site
  file:
    dest: '/etc/nginx/sites-enabled/default'
    state: absent

- name: install docnow site
  template:
    src: 'docnow.nginx.conf'
    dest: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
  notify: restart nginx

- name: enable docnow site
  file:
    src: '/etc/nginx/sites-available/{{ nginx_site_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ nginx_site_name }}.conf'
    state: link
  notify: restart nginx
