---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 600
  vars:
    - db_hostname: "127.0.0.1"
    - db_username: "docnow"
    - db_password: "Change_me"
    - db_name: "docnow_dev"
    - node_env: "production"
    - redis_host: "127.0.0.1"
    - docnow_user: "docnow"
    - users_group_list:
      - name: "{{ docnow_user | default(docnow) }}"
    - users_user_list:
      - name: "{{ docnow_user | default(docnow) }}"
        comment: Docnow User
        sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    - docnow_app_root: "/var/local/docnow_app/docnow/"
  tasks:
    - name: "Include postgesql"
      include_role:
        name: postgresql
      vars:
        postgresql_hba_entries:
          - type: local
            database: all
            user: postgres
            method: ident
          - type: host
            database: all
            user: postgres
            address: 127.0.0.1/32
            method: ident
          - type: host
            database: docnow_dev
            user: docnow
            address: 127.0.0.1/32
            method: md5
        postgresql_databases:
          - name: "docnow_dev"
        postgresql_users:
          - name: "docnow"
            password: "Change_me"
            db: "docnow_dev"
            priv: "ALL"
            role_attr_flags: "SUPERUSER"
    - name: "Include docnow_role"
      include_role:
        name: docnow_role
      vars:
        postgresql_databases:
          - name: "docnow_dev"
        postgresql_users:
          - name: "docnow"
            password: "Change_me"
            db: "docnow_dev"
            priv: "ALL"
            role_attr_flags: "SUPERUSER"
