---
- name: Bastion host | Create bastionhost inbound rules.
  ec2_group:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    description: 'bastion host inbound rules'
    name: 'bastion host name'
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: '{{ my_ip }}/32'
    vpc_id: '{{ vpc_id }}'
  register: bastionhost_inbound_results

- name: Bastion host | Tag bastionhost inbound traffic rules.
  ec2_tag:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    resource: '{{ bastionhost_inbound_results.group_id }}'
    state: present
    tags:
      Name: 'docnow-bastionhost'

- name: Bastion host | Get subnet ID based on subnet variable
  ec2_vpc_subnet_facts:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    filters:
      "tag:Name": "{{ ec2_bastionhost.subnet }}"
  register: vpc_subnet_facts

- name: Bastion host | Create bastionhost instance.
  ec2:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    assign_public_ip: '{{ ec2_bastionhost.assign_public_ip }}'
    count_tag:
      Name: '{{ ec2_bastionhost.instance_tags.Name }}'
    exact_count: '{{ ec2_bastionhost.exact_count }}'
    group: '{{ ec2_bastionhost.groups }}'
    instance_tags: "{{ ec2_bastionhost.instance_tags }}"
    image: '{{ image }}'
    instance_type: '{{ instance_type }}'
    keypair: '{{ keypair }}'
    source_dest_check: 'no'
    vpc_subnet_id: "{{ vpc_subnet_facts.subnets|map(attribute='id')|list|first }}"
    wait: 'yes'
  register: bastionhost_instance_results

- name: Bastion host | Create bastionhost SSH inbound rules for internal
  ec2_group:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    description: "{{ securitygroups_bastionhost_internal.tags.Name }} SSH rules."
    name: "{{ securitygroups_bastionhost_internal.name }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: '{{ my_ip }}/32'
    vpc_id: '{{ vpc_id_fact }}'
  register: bastionhost_inbound_internal_results

- name: Tag bastionhost SSH inbound rules for internal instances
  ec2_tag:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    resource: '{{ bastionhost_inbound_internal_results.group_id }}'
    state: present
    tags: '{{ securitygroups_bastionhost_internal.tags }}'

- name: Bastion host | Set public DNS fact.
  set_fact:
    bastion_public_dns_name: '{{ bastionhost_instance_results.tagged_instances.0.public_dns_name }}'

- name: Bastion host | Print public IP address.
  debug:
    msg: 'bastionhost public DNS: {{ bastion_public_dns_name }}'
