---
- name: reload systemd configuration
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart elasticsearch
  service:
    name: '{{ item }}'
    state: restarted
    enabled: 'yes'
  with_items:
    - elasticsearch
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
