---
- name: Converge
  hosts: all
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 600
  tasks:
    - name: "Include redis"
      include_role:
        name: "redis"
