---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: check redis package status
      apt:
        name: "{{ item }}"
        state: present
      check_mode: true
      register: pkg_status
      loop:
        - redis-server
        - redis-tools
