---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create an Elactic AWS Cluster
Parameters:
  ElasticSearchDomain:
    Default: docnowelasticsearchdomain
    Description: The name of your elasticsearch domain
    Type: String
  ElasticSearchMachineSize:
    Default: m4.large.elasticsearch
    Description: Size of your elasticsearch machine
    Type: String
Resources:
  ElasticsearchDomain:
    Properties:
      AccessPolicies:
        Statement:
          - Action: es:*
            Effect: Allow
            Principal:
              AWS: '*'
            Resource: '*'
        Version: 2012-10-17
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      DomainName:
        Ref: ElasticSearchDomain
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 20
        VolumeType: gp2
      ElasticsearchClusterConfig:
        DedicatedMasterCount: 2
        DedicatedMasterEnabled: 'true'
        DedicatedMasterType:
          Ref: ElasticSearchMachineSize
        InstanceCount: 2
        InstanceType:
          Ref: ElasticSearchMachineSize
        ZoneAwarenessEnabled: 'true'
      ElasticsearchVersion: '5.1'
      SnapshotOptions:
        AutomatedSnapshotStartHour: 0
    Type: AWS::Elasticsearch::Domain
