---
- hosts: localhost
  connection: local
  tasks:
  - name: add keys to AWS
    ec2_key:
        name: '{{ environment_public_ssh_key_name }}'
        key_material: '{{ item }}'
        state: present
        force: false
        region: '{{ vpc_region }}'
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
    with_file: '{{ ssh_public_key }}'

  - name: create security group
    ec2_group:
      name: docnow-dev-group
      description: docnow ssh and docker rules
      region: '{{ vpc_region }}'
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 3000
            to_port: 3000
            cidr_ip: 0.0.0.0/0
      state: present

  - name: create an ec2 instance
    ec2:
      state: present
      image: '{{ image }}'
      instance_type: '{{ instance_type }}'
      wait: 'yes'
      wait_timeout: 600
      key_name: '{{ environment_public_ssh_key_name }}'
      region: '{{ vpc_region }}'
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
    register: ec2

  - debug: var=ec2
  - debug: var=ec2.instances
  - debug: var=ec2.instances[0].public_ip

  - name: add host to manage remotely
    add_host:
        hostname: '{{ item.public_ip }}'
        groupname: 'docnow-test'
    with_items: '{{ ec2.instances }}'

  - name: wait for instance to listen for SSH
    wait_for:
        state: started
        host: '{{ item.public_ip }}'
        port: 22
        delay: 10
        timeout: 360
    with_items: '{{ ec2.instances }}'

- hosts: 'docnow-test'
  gather_facts: no
  user: ubuntu
  tasks:

  - name: install minimal python
    raw: sudo bash -c "test -e /usr/bin/python || (apt install -qy python-minimal aptitude)"

  - name: update cache
    apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

  - name: install packages to allow apt to use https
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl

  - name: add docker's official GPG key
    apt_key:
      url: 'https://download.docker.com/linux/ubuntu/gpg'
      state: present

  - name: add docker repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
      state: present

  - name: install docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: add docker group
    group:
      name: docker
      state: present

  - name: add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: enable docker
    systemd:
      name: docker
      state: started
      enabled: yes
