---
# tasks file for docker_ce
- name: docker_ce | remove any docker installed
  package:
    name: "{{ docker_ce_old }}"
    state: absent

- name: docker_ce | add apt keys
  apt_key:
    url: "{{ docker_ce_apt_key_url }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - apt update cache

- name: docker_ce | install repository for yum
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ item.gpgkey }}"
  loop: "{{ docker_ce_yum_repositories }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "dnf"

- name: docker_ce | install docker pip packages
  pip:
    name: "{{ docker_ce_pip_packages }}"
    state: present
  register: docker_ce_install_docker_pip_packages
  until: docker_ce_install_docker_pip_packages is succeeded

- name: docker_ce | add docker group
  group:
    name: docker
    state: present
    system: true

- name: docker_ce | install docker_ce
  package:
    name: "{{ docker_ce_packages }}"
    state: present
  register: docker_ce_install_docker_ce
  until: docker_ce_install_docker_ce is succeeded

- name: docker_ce | start and enable docker_ce
  service:
    name: "{{ docker_ce_service }}"
    state: started
    enabled: true
