---
scenario:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: docnow-instance
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
