---
- name: Add Elasticsearch apt key.
  apt_key:
    url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main'
    state: present
    update_cache: yes

- name: Install Java Elasticsearch
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - openjdk-8-jdk
    - elasticsearch

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
