---
# handlers file for docnow_role

- name: restart url-fetcher
  service:
    name: url-fetcher
    state: restarted
    enabled: yes

- name: restart tweet-loader
  service:
    name: tweet-loader
    state: restarted
    enabled: yes
