---
galaxy_info:
  namespace: kayiwa
  description: redis role
  company: docnow
  role_name: redis

  license: BSD


  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
    - name: Centos
      versions:
        - 7

dependencies: []
