---
# tasks file for acme_le
- name: acme_le | add certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot
  when: ansible_os_family == Ubuntu

- name: acme_le | Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_os_family == Redhat

- name: acme_le | install certbot Ubuntu
  apt:
    name: ["certbot", "python-certbot-nginx"]
    state: present
    update_cache: true
  when: ansible_os_family == Ubuntu

- name: acme_le | install certbot Centos
  yum:
    name: ["certbot", "python2-certbot-nginx"]
    state: present
  when: ansible_os_family == Redhat

- include_tasks: manage.yml
- include_tasks: test.yml
