---
# tasks file for acme_le
- name: acme_le | install certbot
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - python-certbot-nginx

- name: acme_le | create letsencrypt directory
  ansible.builtin.file:
    name: "/var/www/letsencrypt"
    state: directory
    mode: 0644

- name: acme_le | Create letsencrypt certificate
  ansible.builtin.shell: certbot certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/archive/{{ domain_name }}

- name: acme_le | Generate dhparams
  ansible.builtin.shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: acme_le | install LE requests
  ansible.builtin.template:
    src: docnow_le_nginx.conf.j2
    dest: "/etc/nginx/sites-available/docnow_le_nginx.conf"

- name: acme_le | remove docnow non-https site
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/docnow_app
    state: absent

- name: acme_le | create symbolic link
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/docnow_le_nginx.conf"
    dest: "/etc/nginx/sites-enabled/docnow_le_nginx.conf"
    state: link

- name: acme_le | nginx to activate docnow site
  ansible.builtin.service:
    name: nginx
    state: restarted
