---
- name: Bastion host | Get subnet facts.
  ec2_vpc_subnet_facts:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    filters: '{{ filters }}'
  register: subnet_facts

- name: output subnet facts
  debug:
    msg: '{{ subnet_facts.subnets }}'

- name: output subnet facts
  debug:
    msg: '{{ subnet_facts.subnets.0.id }}'

- name: Bastion host
  set_fact:
    vpc_id_fact: "{{ subnet_facts.subnets.0.id }}"
