---
- name: upload your rsa key
  ec2_key:
    name: '{{ keypair }}'
    region: '{{ vpc_region }}'
    key_material: '{{ item }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
  with_file: ~/.ssh/id_rsa.pub

- name: create docnow security group
  ec2_group:
    name: '{{ security_groups }}'
    region: '{{ vpc_region }}'
    description: 'the docnow ssh group'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Search for the latest Ubuntu Xenial AMI
  ec2_ami_find:
    region: '{{ vpc_region }}'
    name: 'ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*'
    owner: 099720109477
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result

- name: Launch new instance
  ec2:
    region: '{{ vpc_region }}'
    keypair: '{{ keypair }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    zone: '{{ zone }}'
    group: '{{ security_groups }}'
    image: '{{ ami_result.results[0].ami_id }}'
    instance_type: '{{ instance_type }}'
    instance_tags:
      Name: '{{ name }}'
    volumes: '{{ volumes }}'
    wait: 'yes'
  register: ec2

- debug: var=ec2

- debug: var=ec2.instances

- debug: var=ec2.instances[0].public_ip


- name: Add new instances to host group
  add_host:
    name: '{{ item.public_dns_name }}'
    groups: '{{ name }}'
    ec2_id: '{{ item.id }}'
  with_items: '{{ ec2.instances }}'

- name: Wait for instance to boot
  wait_for:
    host: '{{ item.public_dns_name }}'
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: '{{ ec2.instances }}'
