---
# tasks file for users
#
- name: user | install essential
  apt:
    name: ["build-essential", "git"]
    state: present
    update_cache: true

- name: user | loop over users_group_list
  include: group.yml
  loop: "{{ users_group_list }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - users_group_list is defined

- name: user | loop over users_user_list
  include: user.yml
  loop: "{{ users_user_list }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - users_user_list is defined
