---
# tasks file for users
- name: loop over users_group_list
  include: group.yml
  loop: "{{ users_group_list }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - users_group_list is defined

- name: loop over users_user_list
  include: user.yml
  loop: "{{ users_user_list }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - users_user_list is defined