---
# defaults file for postgresql
postgresql_port: 5432
postgresql_listen_addresses: 127.0.0.1
postgresql_unix_socket_directories: /var/run/postgresql
postgresql_max_wal_size: 1GB
postgresql_min_wal_size: 80MB
postgresql_log_timezone: UTC
postgresql_datestyle: iso, ymd
postgresql_timezone: UTC
postgresql_default_text_search_config: pg_catalog.english

postgresql_hba_entries:
  - type: local
    database: all
    user: all
    method: peer
  - type: host
    database: all
    user: all
    address: 127.0.0.1/32
    method: ident
  - type: host
    database: all
    user: all
    address: ::1/128
    method: ident
  - type: local
    database: replication
    user: all
    method: peer
  - type: host
    database: replication
    user: all
    address: 127.0.0.1/32
    method: ident
  - type: host
    database: replication
    user: all
    address: ::1/128
    method: ident
