---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 600
  vars:
    - docnow_app_root: "/var/local/docnow_app/docnow/"
    - db_hostname: "127.0.0.1"
    - db_username: "docnow"
    - db_password: "Change_me"
    - db_name: "docnow_dev"
    - node_env: "production"
    - redis_host: "127.0.0.1"
    - docnow_user: "docnow"
    - users_group_list:
      - name: "{{ docnow_user | default(docnow) }}"
    - users_user_list:
      - name: "{{ docnow_user | default(docnow) }}"
        comment: Docnow User
        sudo_options: "ALL=(ALL) NOPASSWD: ALL"
  tasks:
    - name: "Include nginx"
      include_role:
        name: nginx
