---
- name: place authorized_key for {{ user.name }}
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ item }}"
  loop: "{{ user.authorized_keys }}"
  loop_control:
    label: "{{ item | basename }}"
