---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 600
  tasks:
    - name: "Include nodejs"
      include_role:
        name: nodejs
