---
- hosts: localhost
  gather_facts: false
  environment:
    SCW_API_KEY: "{{ scw_api_key }}"
  vars_files:
    - ../group_vars/scaleway/vars.yml
  tasks:
    - name: Create a docnow server
      scaleway_compute:
        name: docnow_vm
        state: present
        image: 6651f88f-45af-4b93-95e8-3931b74f6acc
        organization: "{{ organization_id }}"
        region: par1
        commercial_type: DEV1-XL
        tags:
          - docnow
          - app

    - name: create scaleway ssh key
      scaleway_sshkey:
        ssh_pub_key: "{{ your_ssh_rsa_public_key }}"
        state: present
      register: result

    - assert:
        that:
          - result is success and result is changed


- hosts: scaleway
  remote_user: root
  become: true
  vars_files:
    - ../group_vars/scaleway/vars.yml
  tasks:
  roles:
    - role: roles/nginx
