---
- hosts: scaleway
  remote_user: root
  become: true
  debugger: on_failed
  vars:
    users_group_list:
      - name: docnow

    users_user_list:
      - name: docnow
        comment: Docnow User
        group: docnow
        sudo_options: "ALL=(ALL) NOPASSWD: ALL"

    docnow_user: "docnow"

  roles:
    - role: roles/nginx
