---
# tasks file for docnow_role
#
- name: Docnow | Make repos safe
  ansible.builtin.command: git config --global --add safe.directory '{{ item }}'
  become: true
  loop:
    - "{{ docnow_app_home }}/docnow"
  changed_when: false

- name: Docnow | Clone Docnow appraisal app
  ansible.builtin.git:
    repo: "https://github.com/docnow/docnow.git"
    version: "{{ docnow_version }}"
    dest: "{{ docnow_app_home }}/docnow"
    clone: true
    update: true
    force: true
  become: true
  tags: deploy

- name: Docnow | change permissions
  ansible.builtin.file:
    path: "{{ docnow_app_home }}/docnow"
    state: directory
    recurse: true
    owner: "{{ docnow_user | default(docnow) }}"
    group: "{{ docnow_user | default(docnow) }}"
    mode: 0755
  changed_when: false
  tags: deploy

- name: Docnow | install node environment settings
  ansible.builtin.template:
    src: env.production.j2
    dest: "{{ docnow_app_home }}/docnow/.env.production"
    mode: 0644
  changed_when: false
  tags: deploy

- name: Docnow | Symbolic Link
  ansible.builtin.file:
    src: "{{ docnow_app_home }}/docnow/.env.production"
    dest: "{{ docnow_app_home }}/docnow/.env"
    state: link
  tags: deploy

- name: Docnow | Symbolic Link for public
  ansible.builtin.file:
    src: "{{ docnow_app_home }}/docnow/userData"
    dest: "{{ docnow_app_home }}/docnow/public"
    state: link
  tags: deploy

- name: Docnow | install modules
  ansible.builtin.command: npm install --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"
  tags: deploy

- name: Docnow | prune modules
  ansible.builtin.command: npm prune --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"
  tags: deploy

- name: Docnow | webpack installation
  ansible.builtin.command: npm install --save-dev webpack-dev-middleware webpack-hot-middleware
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"
  tags: deploy

- name: Docnow | tweet-loader configuration
  ansible.builtin.template:
    src: tweet-loader.service.j2
    dest: "/etc/systemd/system/tweet-loader.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart tweet-loader
  tags: deploy

- name: Docnow | url-fetcher configuration
  ansible.builtin.template:
    src: url-fetcher.service.j2
    dest: "/etc/systemd/system/url-fetcher.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart url-fetcher
  tags: deploy

- name: Docnow | Stop app (before db migration)
  ansible.builtin.service:
    name: nginx
    state: stopped
  notify:
    - restart nginx
  tags: deploy

- name: Docnow | Stop tweet-loader (before db migration)
  ansible.builtin.service:
    name: tweet-loader
    state: stopped
  notify:
    - restart tweet-loader
  tags: deploy

- name: Stop url-fetcher (before db migration)
  ansible.builtin.service:
    name: url-fetcher
    state: stopped
  notify:
    - restart url-fetcher
  tags: deploy

- name: Docnow | migrate and createdb
  ansible.builtin.command: npm run migrate
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"
  tags: deploy
