---
# tasks file for docnow_role

- name: Docnow | Clone Docnow appraisal app
  git:
    repo: "https://github.com/docnow/docnow.git"
    version: "{{ docnow_version }}"
    dest: "{{ docnow_app_home }}/docnow"
    clone: true
    update: true
    force: true
  become: true

- name: Docnow | change permissions
  file:
    path: "{{ docnow_app_home }}/docnow"
    state: directory
    recurse: true
    owner: "{{ docnow_user | default(docnow) }}"
    group: "{{ docnow_user | default(docnow) }}"
    mode: 0755
  changed_when: false

- name: Docnow | install node environment settings
  template:
    src: env.production.j2
    dest: "{{ docnow_app_home }}/docnow/.env.production"
    mode: 0644
  changed_when: false

- name: Docnow | Symbolic Link
  file:
    src: "{{ docnow_app_home }}/docnow/.env.production"
    dest: "{{ docnow_app_home }}/docnow/.env"
    state: link

- name: Docnow | Symbolic Link for public
  file:
    src: "{{ docnow_app_home }}/docnow/userData"
    dest: "{{ docnow_app_home }}/docnow/public"
    state: link

- name: Docnow | install modules
  command: npm install --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"

- name: Docnow | prune modules
  command: npm prune --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"

- name: Docnow | webpack installation
  command: npm install --save-dev webpack-dev-middleware webpack-hot-middleware
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"

- name: Docnow | tweet-loader configuration
  template:
    src: tweet-loader.service.j2
    dest: "/etc/systemd/system/tweet-loader.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart tweet-loader

- name: Docnow | url-fetcher configuration
  template:
    src: url-fetcher.service.j2
    dest: "/etc/systemd/system/url-fetcher.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart url-fetcher

- name: Stop app (before db migration)
  service: name=nginx state=stopped
  notify:
    - restart nginx

- name: Stop tweet-loader (before db migration)
  service: name=tweet-loader state=stopped
  notify:
    - restart tweet-loader

- name: Stop url-fetcher (before db migration)
  service: name=url-fetcher state=stopped
  notify:
    - restart url-fetcher

- name: Docnow | migrate and createdb
  command: npm run migrate
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true
  become_user: "{{ docnow_user }}"
