---
# tasks file for docnow_role
- name: Docnow | Clone Docnow appraisal app
  git:
    repo: "https://github.com/docnow/docnow.git"
    version: 'master'
    dest: "{{ docnow_app_home }}/docnow"
    clone: true
    update: true
  become: true

- name: Docnow | install node environment settings
  template:
    src: env.production.j2
    dest: "{{ docnow_app_home }}/docnow/.env.production"
    mode: 0644

- name: Docnow | Symbolic Link
  file:
    src: "{{ docnow_app_home }}/docnow/.env.production"
    dest: "{{ docnow_app_home }}/docnow/.env"
    state: link

- name: Docnow | Symbolic Link for public
  file:
    src: "{{ docnow_app_home }}/docnow/userData"
    dest: "{{ docnow_app_home }}/docnow/public"
    state: link

- name: Docnow | install modules
  command: npm install --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
  become: true

- name: Docnow | prune modules
  command: npm prune --production
  args:
    chdir: "{{ docnow_app_home }}/docnow"
  changed_when: false
