---
- hosts: docnow_demo
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/docnow/dev.yml
  roles:
    - role: ../roles/acme_le

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #development
