---
- hosts: docnow_demo
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/docnow/dev.yml
    - ../group_vars/docnow/vault.yml
  roles:
    - role: ../roles/acme_le

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_docnow_slack_token }}"
        msg: "smoketest deployed"
        channel: #development
      tags: deploy
