---
- hosts: gcp
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/docnow_id_rsa"
  vars_files:
    - ../group_vars/gcp/vars.yml
  tasks:
  roles:
    - role: roles/docnow_role
