---
- hosts: aws
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/LightSailKeyPair.pem"
  vars_files:
    - ../group_vars/aws/vars.yml
  tasks:
  roles:
    - role: roles/docnow_role
