---
name: Molecule Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - users
          - redis
          - postgresql
          - nodejs
          - docnow_role
    steps:
      - name: Checkout branch
        run: |
          git config --global http.postBuffer 1048576000
          for i in 1 2 3 4 5; do git clone https://github.com/docnow/docnow-ansible.git . && break || sleep 15; done
          git checkout ${{ github.sha }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Disable apparmor
        run: |
          sudo service apparmor stop
          sudo service apparmor teardown
          sudo /usr/sbin/update-rc.d -f apparmor remove
      - name: Run tests
        run: |
          ROLE=${{ matrix.role }} python run_molecule.py
